### PR TITLE
Added time restricted mode

### PR DESCRIPTION
**Pull request by Abhishek150598**
1. Added a 60 second timer.
2. Timer turns red when 10 seconds are left.
3. Added a time restricted mode button in the intro menu.

### CODE REVIEW

**Review by sriyash421 — CHANGES_REQUESTED** [review]
Amazing work!!
It seems you have hardcoded the values for the new button. Please adjust the position of the PLAY_TIMED button by making it centre±width/2 in coordinates.

And can you explain me the changes in assets binary shown here.

**Comment by Abhishek150598** [comment]
I was getting some warnings on terminal screen in Ubuntu as follows:
`libpng warning: iCCP: known incorrect sRGB profile`

To remove this I applied mogrify *.png as suggested here:
[https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile](url)

I have made the changes to the button coordinates.

**Comment by sriyash421** [comment]
You also need to disable the no. of misses count as I don't want the game to end before 60s.

**Comment by Abhishek150598** [comment]
Done.

**Comment by sriyash421** [comment]
Great Job! Thanks for contributing to the project.

**Pull request merged**
