### PR TITLE
display made dynamic

### PR DESCRIPTION
**Pull request by shellkore**
WIDTH and HEIGHT now set from `pygame.display.Info()` . This detects the size of your screen and then width and height are set accordingly.

### CODE REVIEW

**Review by sriyash421 — CHANGES_REQUESTED** [review]
Great work! Just a few changes.
Make the HEIGHT and WIDTH smaller than the screen and not exactly same.
Don't add any functions to the constants.py file. Just initialize h,w as None here and modify them elsewhere.

**Comment by shellkore** [comment]
Shifted dynamic display code in main.py and decreased size by 20 from width and height.

**Review by sriyash421 — CHANGES_REQUESTED** [review]
Nice work. I know it might feel a bit frustrating doing these changes but I want your contributions to be perfect on this project.
Since we are importing the constants file in game.py  and importing that in main.py, don't you think the code is redundant and you could create a function for it in game.py.

**Comment by shellkore** [comment]
HEIGHT and WIDTH declared in game.py. Code is working fine.

**Comment by sriyash421** [comment]
Great work! Thanks for contributing to  this project.

**Pull request merged**
