### PR TITLE
Add instructions option to game screen

### PR DESCRIPTION
**Pull request by PavitKaur05**
Added instructions option on game screen
Screenshot from 2019-12-07 13-39-04
Screenshot from 2019-12-07 13-39-11

### CODE REVIEW

**Review by sriyash421 — CHANGES_REQUESTED** [review]
Great work! Nice job, but just a few changes needed then we can merge this pr.
Just add the background color to the constants file.
And create a separate issue for unnecessary boxes in the pause and instructions menu on the top left corner.

**Comment by PavitKaur05** [comment]
> Great work! Nice job, but just a few changes needed then we can merge this pr.
> Just add the background color to the constants file.
> And create a separate issue for unnecessary boxes in the pause and instructions menu on the top left corner.

Ok .I will do it.

**Comment by PavitKaur05** [comment]
@sriyash421 I have made the changes requested.Please review it again.

**Comment by sriyash421** [comment]
Thanks for contributing to this project.

**Comment by PavitKaur05** [comment]
> Thanks for contributing to this project.

Happy to be a part of this. :)

**Pull request merged**
